server:
  port: 8088


spring:
  #datasource
  datasource:
    url: jdbc:mysql://localhost:3306/mvn?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #aop
  aop:
    auto: true
    proxy-target-class: false
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    pool:
      maxActive: 8
      maxWait: -1
      maxIdle: 8
      minIdle: 0
